version: "3.8"

services:
  roa-postgres:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile.postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}" #automatically defined in environment once run in heroku
  roa-express:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile.express
    ports:
      - "${PORT}:${PORT}"
  roa-bootstrapping:
    env_file: .env
    depends_on:
      - roa-postgres
      - roa-express
    build:
      context: ./
      dockerfile: Dockerfile.bootstrapping
