version: "3.8"

services:
  roa-postgres:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
  roa-express:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile.express
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
  roa-bootstrapping:
    env_file: .env
    depends_on:
      - roa-postgres
      - roa-express
    build:
      context: ./
      dockerfile: Dockerfile.bootstrapping
